version: '2'
services:
    biz-mysql:
        image: mysql:5.7.20
        volumes:
            - ~/volumes/jhipster/biz/mysql/:/var/lib/mysql/
            - ./init-db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=biz
            - MYSQL_PASSWORD=biz
            - MYSQL_DATABASE=biz
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
